project_structure:
    build: brownie/build
    contracts: contracts
    interfaces: contracts/interfaces
    reports: brownie/reports
    scripts: brownie/scripts
    tests: brownie/tests

dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.3.0

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.3.0"
